<div style="font-family: Segoe UI;">
    <header style="background:#343A40;margin:auto;width:100%;height:75px;font-size:20px;color:#FFF;text-align:center;line-height:75px;font-weight:bold;">{!! $nombre_de_la_empresa_abreviado !!}<br></header><p></p><p><span style="font-family: " segoe="" ui";"="">
    </span></p><section style="width: 70%; margin: 40px auto 20px; font-size: 16px;"><span style="color: rgb(99, 99, 99);"><span style="" segoe="" ui";"="">
    </span></span></section></div><div style="font-family: &quot;Segoe UI&quot;; line-height: 1;"><div style="text-align: center;"><img src="https://s3.us-west-2.amazonaws.com/archivos.arconesycanastas/sistema/pYS4gxM7u1kMhZLHVhMDeba5zXM87X67t9ZPGqHF.png" style="font-size: 0.875rem; width: 286px; height: 117.441px;"></div><section style="width: 70%; margin: 40px auto 20px; font-size: 16px;"><span style="color: rgb(99, 99, 99);"><strong style="font-size: 20px;"><span style="" segoe="" ui";"="">Estimado/a {!! $nombre_del_usuario !!}</span></strong></span></section><p></p><p></p><section style="width: 70%; margin: 40px auto 20px; font-size: 16px;"><span style="color: rgb(99, 99, 99);">Recibimos una solicitud de restablecimiento de contraseña.&nbsp;</span><br style="color: rgb(132, 132, 132);"><span style="color: rgb(99, 99, 99);">Su clave única de acceso es <b>{!!$clave_unica!!}&nbsp;</b>, por favor ingrésela&nbsp;en el siguiente enlace.</span></section></div><div style="font-family: Segoe UI;"><section style="width: 70%; margin: 40px auto 20px; font-size: 16px;"><span style="color: rgb(99, 99, 99);"><span style="color: rgb(99, 99, 99);"><span style="" segoe="" ui";"="">
    <center><a href="{!! $pagina_de_inicio_del_sistema !!}" target="_blank" style="background:#3490DC;color:#FFF; border-radius:0.2rem;padding:0.5rem">Acceder a la plataforma</a></center></span></span></span></section></div><div style="font-family: &quot;Segoe UI&quot;; line-height: 1;"><section style="width: 70%; margin: 40px auto 20px; font-size: 16px;"><span style="color: rgb(99, 99, 99);"><span style="color: rgb(99, 99, 99);"><span style="" segoe="" ui";"=""><center><span style="text-align: left;">Si usted no ha hecho esta solicitud, puede ignorar o eliminar este e-mail.</span><br></center></span></span></span></section></div><div style="font-family: &quot;Segoe UI&quot;; line-height: 1;"><section style="width: 70%; margin: 40px auto 20px; font-size: 16px;"><span style="color: rgb(99, 99, 99);"><span style="color: rgb(99, 99, 99);"><span style="" segoe="" ui";"=""><center><br></center>Saludos,</span><span style="color: rgb(99, 99, 99);"><span style="color: rgb(99, 99, 99);"><span style="" segoe="" ui";"=""><br></span><a href="{!! $pagina_web_de_la_empresa !!}" target="_blank" style=""><span style="" segoe="" ui";"="">{!! $nombre_de_la_empresa_abreviado !!}</span></a></span><span style="color: rgb(132, 132, 132);" segoe="" ui";"="">
    <hr>
    <strong>Este correo es enviado automáticamente por el sistema de {!! $nombre_de_la_empresa_abreviado !!}</strong><br>
    Si tienes problemas al acceder o haciendo clic en el botón, copia y pega el siguiente enlace en tu navegador: {!! $pagina_de_inicio_del_sistema !!}
    </span></span></span></span></section><span style="font-family: " segoe="" ui";"="">
    </span><p></p><footer style="background:#343A40;margin:auto;width:100%;height:75px;font-size:14px;color:#FFF;text-align:center;line-height:75px;"><span style="font-family: " segoe="" ui";"="">
    {!! $nombre_de_la_empresa_abreviado !!} - Copyright © {!! $year_de_inicio_de_la_empresa !!} - {!! $year_actual !!}. Todos los derechos reservados.</span>
    </footer>
    </div>